### ISSUE TITLE
Minimum PHP version required to run the integration example ?

### ISSUE THREAD

**Issue by graceman9** [csob/paymentgateway#125]
Which version of PHP is required to run PHP example 1.5 ?

**Comment by graceman9** [comment]
I guess it should be `PHP-5.4` because of this:

    // PHP 5.4.0 New features:
    // * Class member access on instantiation has been added, e.g. (new Foo)->bar().
    // http://docs.php.net/manual/en/migration54.new-features.php
    $dttm = (new DateTime ())->format ( "YmdHis" );

**Comment by Miculka** [comment]
Hello.



Yes, you are right. Our paymentgateway support PHP – 5.4.



Regards


*Ing. Michal Mičulka*IT support specialist

[image: http://www.monetplus.cz/data/images/Monet_tagline_CMYK.png]
*E:* mmiculka@monetplus.cz



*From:* graceman9 [mailto:notifications@github.com]
*Sent:* Thursday, January 21, 2016 9:17 PM
*To:* csob/paymentgateway <paymentgateway@noreply.github.com>
*Subject:* Re: [paymentgateway] Server's system requirements? (#125)



I guess it should be PHP-5.4 because of this:

// PHP 5.4.0 New features:

// * Class member access on instantiation has been added, e.g. (new Foo)->bar().

// http://docs.php.net/manual/en/migration54.new-features.php

$dttm = (new DateTime ())->format ( "YmdHis" );

—
Reply to this email directly or view it on GitHub
<https://github.com/csob/paymentgateway/issues/125#issuecomment-173695625>.
