### ISSUE TITLE
Payment URL lifetime - expires too quickly?

### ISSUE THREAD

**Issue by graceman9** [csob/paymentgateway#137]
I tried to use a little part of the CSOB API - the idea was to create a script generating payment URL to use it manually.

But when I finished the script I got additional requirements: 
URL should work at least 2 day since it was generated.

I can see that URLs are expiring in about 30 min after they were created and the bank says 404 (payment not found).

Please answer whether we can or not to control URL lifetime?

**Comment by janbrasna** [comment]
The time-to-live is indeed fixed at 30mins.

Maybe if you describe the case you want to address to your banker, he might be able to escalate that for consideration to the gateway team?  What's the situation for 48h TTL in your case?

**Comment by graceman9** [comment]
As I described above our payments are processed manually.
We want to send payment link to our clients via email.
They have to pay, and then they will return to our success page.
But it's hard for them to pay in 30 min.

So we decided to create a form, where users can manually enter their order number and amount. But this not implemented yet, and as for us - it will be easier to just increase TTL.

What exactly I have to describe?

**Comment by janbrasna** [comment]
The business case I guess.

Because this might not work in the scenario you intend. Once you render the payment page, the payment is locked for that user/IP only, so your client won't be able to open that payment URL from an e-mail.

The correct way would be linking your own payment page from the e-mail, i.e. generating the orders/links like `example.com/pay?oder=123&amount=1000` which would only then invoke/init new payment for that particular customer (no need for users to fill anything). Any other way sounds like a bad anti-pattern TBH. The customer must be sure *he* invoked the payment.

**Comment by graceman9** [comment]
I got it, thanks.
