### ISSUE TITLE
Verification error

### ISSUE THREAD

**Issue by trendak** [csob/paymentgateway#544]
Hi,
I'm using keygen (https://iplatebnibrana.csob.cz/keygen) to generate a keys. I am using an anonymous option. And i use driver to Omnipay https://github.com/bileto/omnipay-csob.

When i try make payment init i have error "Verification error, the signature cannot be verified with given public key"
`Array ( [merchantId] => A5050KhR23 [orderNo] => 9102 [dttm] => 20201229170235 [payOperation] => payment [payMethod] => card [totalAmount] => 1500000 [currency] => CZK [closePayment] => 1 [returnUrl] => http://orderingpayment.test/web/gateway-return.php [returnMethod] => POST [cart] => Array ( [0] => Array ( [name] => Notebook [quantity] => 1 [amount] => 1500000 [description] => Lenovo ThinkPad Edge E540... ) [1] => Array ( [name] => Shipping [quantity] => 1 [amount] => 0 [description] => PPL ) ) [description] => Shopping at myStore.com (Lenovo ThinkPad Edge E540, Shipping with PPL) [merchantData] => [customerId] => [language] => CZ [signature] => YJ+rwm0GhxvYyNmjM2YrIhp1zuWM8JVOQHu1VGHv+iB5omIV2ZeRP7y0sSiHffpE2TjRv/lcyC7euEq4BuJne/nZfKFNYP7S2+NjKpMP+juDDOfugsR/kv/8Px5RcyTW6tK0F1FC9MVNmRZYBp68uj87M7bxc424TEhAQfWzcjhqNAIjXUd/kSHyE6nayQlIln8B50Ep6XaOJpvJtzGVqYsn8LHHahfnOiF9wvMdai4Cc9ON7C1XMowtdH4MJQgEUsVDGPqtyVminl8UgvhoyCMpwK9EfoOq7lobzCsBKHn1xlJcOo6LL7YuME5SZRle2u4E+VvEa4PVe+YJsQPCXw== )`

What could be wrong?

**Comment by Mspisar** [comment]
Hello,

your request has been registered and forwarded to responsible service technician. You will be contacted as soon as possible.

best regards

Milan Spisar

**Comment by trendak** [comment]
I also have a question, how can a customer create an account?

**Comment by dkomarek2** [comment]
Good day,

I couldn't find your "[dttm] => 20201229170235" test.

But I see that some attempts to create a transaction were successful.
**For example:**
_December 30th 2020, 10:33:16.213 | Received paymentInit request A5050KhR23 / 8c13f6ca76532FL, orderNo 9102_
But the transaction did not start processing because the payment gateway did not receive a "paymentProcess" request. Then, after about 30 minutes, this transaction expired.

I checked your last attempt which ended with error "400". He arrived at the payment gateway in "2020-12-30 10:56:17,966".
There is a problem:
"merchantData": null,
    "customerId": null,

These are optional parameters, so if you do not want to fill them with real data, do not specify them at all.

In a successful attempt, the data looked like this:
"merchantData": "",
    "customerId": "",

But the correct form is to fill in real data or not to specify an optional parameter at all.
Please check the implementation of these items in the implementation and correct it.

For more convenient communication and sending test data, I suggest using email.
You can write me and send the sent data to email dkomarek@monetplus.cz

Thank you.

Best regards,

Daniel Komárek
IT application specialist
