### ISSUE TITLE
Apple Pay - na testovacím prostředí prochází jen jedna platební karta

### ISSUE THREAD

**Issue by mdonef** [csob/paymentgateway#595]
Dobrý den,

po vygenerování nových certifikátů pro ApplePay (testovací prostředí) prochází jen jedna konkrétní platební karta a ostatní jsou zamítnuty. V minulosti bylo vše OK. Je to vůbec možné? ID brány je M1MIPS8674

Děkuji

**Comment by Mspisar** [comment]
Dobrý den,

Váš dotaz jsme zaevidovali a předali k řešení. O dalším postupu budete kontaktován odpovědným kolegou.

S pozdravem

Milan Spisar
1st level support - Team Leader

**Comment by mrazekl** [comment]
Dobrý den,
zkontroloval jsem vaše neúspěšné požadavky a končí s chybou, že BIN použité tokenizované karty v zařízení nebyl nalezen v testovací databázi. 
K hledání použitého BINu dochází, pokud se v payloadu nevyskytuje hodnota eci.
Je možné že se něco změnilo při tokenizaci karet v zařízení a ne vždy je tato hodnota odesílána, přičemž dříve tomu takhle mohlo být. 
Ještě jsem předal programátorovi k analýze.

**Comment by mdonef** [comment]
> Dobrý den,
> zkontroloval jsem vaše neúspěšné požadavky a končí s chybou, že BIN použité tokenizované karty v zařízení nebyl nalezen v testovací databázi.
> K hledání použitého BINu dochází, pokud se v payloadu nevyskytuje hodnota eci.
> Je možné že se něco změnilo při tokenizaci karet v zařízení a ne vždy je tato hodnota odesílána, přičemž dříve tomu takhle mohlo být.
> Ještě jsem předal programátorovi k analýze.

**Comment by mdonef** [comment]
Děkuji, 
chápu to tedy správně, že pro to aby se ECI posílalo nemohu nic udělat?

**Comment by mrazekl** [comment]
Myslím že více či méně ne. Tohle je vlastně příznak, který se přidávádo autorizace, jakým způsobem byl uživatel ověřen a generuje se tuším přímo z jádra zařízení.
Ještě to proberu s programátorem, když se jedná o testovací prostředí, jestli bychom tomu nemohli nějak uhnout.

**Comment by janbrasna** [comment]
citace z [ Developer: Payment Token Format Reference](https://developer.apple.com/library/archive/documentation/PassKit/Reference/PaymentTokenJSON/PaymentTokenJSON.html#//apple_ref/doc/uid/TP40014929-CH8-SW5):

eciIndicator | string | Optional. ECI indicator, as defined by 3-D Secure: The card network may add an ECI indicator to the card data. This indicator is then included in the payment token. If you receive an ECI indicator, you must pass it on to your payment processor; otherwise, the transaction fails.
-- | -- | --

Prostredi neprostredi… ten kryptogram by takto dorazil i na produkci, a je divne, ze by v nasich koncinach issuer eci neposilal. (Nebo ze by ho iOS/SecureElement vyplnovat ruzne v case… to je zajimave.) — A klic se z payloadu ztratit nemohl, protoze je v encrypted casti pod tajemstvim pro transport.

Domenka je, ze se eci posila nejen podle toho, jak silne byl drzitel karty overen pri ukladani do walletu, ale i jak byl overen pri vytazeni z walletu, k tomu ale nikde neexistuje ani dokumentace, ani (oficialni ci neoficialni) vyjadreni, bude to nejake interni tajemstvi asociaci a Applu.

Samotny token se muze refreshnout pri napr. pridani do dalsiho zarizeni atp., takze sam jako takovy se mohl zmenit klidne na pozadi, probiha tam jakysi refresh na push update walletu na icloud uctu, prip. banka sama si muze pushovat ten refresh, kdyz chce vyzadat ulozeni nejakych zmen parametru. Nezacalo se to zamitat az po napr. pridani karty na jine zarizeni? Nebo odebrani a nove pridani? (Klidne se mohlo stat, ze se stejna plastova karta v jinem case ztokenizovala do uplne jineho rozsahu te vygenerovane, ap.)

Asi s tim nic moc nevymyslime, ale pro zajimavost se zkusime podivat, zda se stejny vydavatel nechova nejak podobne obecne. Muzete prosim poslat prvnich 6 znaku z tech karet co vam delaji problemy (a pro kontrolu vydavatelskou banku a typ debit/kredit/gold/commercial), abychom se podivali, co o nich vidime?

**Comment by mdonef** [comment]
Děkuji za vyjádření,

nefungují např. karty
ČSOB, 5451 19, kredit
RB, 5315 33, kredit
RB, 5168 72, debit gold
Revolut 5273 46, debit

Funguje:
ČSOB, 4910 80, debit

**Comment by janbrasna** [comment]
@mdonef Diky, jen potvrzuji ze to jsou rozsahy, o kterych zcasti uz z drivejska vime ze se nam vraceji jako nezname ci nekonkretni (sedi i vydavatele/produkty, nektere z nich dlouhodobe interne pro tento problem pouzivame), proto i ten fallback pri nizkem eci dopada jak dopada. Je to vicemene jen vysledek logiky simulatoru, ale duvod je daleko vice systemovy, a ten resime dlouhodobe.

Zvladate i s timto omezenim testovat, nebo byste radeji, kdyby vsechny vysledky, rekneme tedy i zamitave, simulator stejne prezentoval jako uspesne?

**Comment by janbrasna** [comment]
Vyreseno zmenou logiky simulatoru, nove se vsechny tokeny v sandboxu budou na pozadi menit na "happy path" a o jejich osudu budou rozhodovat OTP overeni a simulovane scenare dle parametru platby. Tento problem s produkcnimi platebnimi daty ktere narazi na moznosti simulatoru by mel s pristim releasem zcela zmizet, bude se "obchazet".
